import { useState } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { ChevronDown, HelpCircle, Phone, ArrowRight } from 'lucide-react';

const faqItems = [
  {
    id: 1,
    question: 'What is MandiMitra?',
    answer: 'MandiMitra is a smart crop-selling decision support platform that helps farmers make better decisions about where and when to sell their produce.'
  },
  {
    id: 2,
    question: 'How does MandiMitra help farmers?',
    answer: 'MandiMitra uses mandi prices, historical trends, and market information to provide simple insights and recommendations to farmers.'
  },
  {
    id: 3,
    question: 'What crops are supported?',
    answer: 'MandiMitra initially focuses on crops such as onion, tomato, and potato, with more crops planned in the future.'
  },
  {
    id: 4,
    question: 'Can MandiMitra predict future crop prices?',
    answer: 'MandiMitra uses historical market data and machine learning to estimate possible future price trends. These predictions are estimates and are not guaranteed.'
  },
  {
    id: 5,
    question: 'What does “Sell Today” or “Wait” mean?',
    answer: 'These recommendations are generated by analyzing available market data and price trends to help farmers decide whether selling now or waiting may be more beneficial.'
  },
  {
    id: 6,
    question: 'Does MandiMitra guarantee a higher selling price?',
    answer: 'No. MandiMitra provides data-driven insights and recommendations, but actual market prices can change due to demand, supply, weather, and other factors.'
  },
  {
    id: 7,
    question: 'Is MandiMitra free to use?',
    answer: 'Yes, the core MandiMitra platform is designed to provide farmers with easy access to useful market insights.'
  },
  {
    id: 8,
    question: 'How can I contact MandiMitra?',
    answer: (
      <span>
        You can contact us at <a href="tel:8850347147" className="text-primary-600 font-semibold hover:underline">8850347147</a> or through our <Link to="/#contact" className="text-primary-600 font-semibold hover:underline">Contact Us</Link> page.
      </span>
    )
  }
];

const FAQPage = () => {
  const [openIndex, setOpenIndex] = useState(0); // Open first by default

  const toggleAccordion = (index) => {
    setOpenIndex(openIndex === index ? -1 : index);
  };

  return (
    <div className="min-h-screen flex flex-col bg-white font-sans text-gray-800">
      <Navbar />

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
        {/* Header */}
        <div className="text-center space-y-4 mb-12">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full text-xs font-semibold bg-primary-100 text-primary-700 uppercase tracking-wider">
            <HelpCircle className="w-3.5 h-3.5" />
            Support & Help
          </div>
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-gray-900 tracking-tight">
            Frequently Asked Questions
          </h1>
          <p className="text-gray-600 text-base sm:text-lg max-w-2xl mx-auto">
            Find answers to common questions about MandiMitra, market rates, and crop-selling recommendations.
          </p>
        </div>

        {/* Accordion FAQ List */}
        <div className="space-y-4">
          {faqItems.map((item, index) => {
            const isOpen = openIndex === index;
            return (
              <div 
                key={item.id}
                className={`border rounded-2xl transition-all duration-200 overflow-hidden ${
                  isOpen ? 'border-primary-300 bg-primary-50/20 shadow-sm' : 'border-gray-200 bg-white hover:border-gray-300'
                }`}
              >
                <button
                  onClick={() => toggleAccordion(index)}
                  className="w-full px-6 py-5 text-left flex justify-between items-center gap-4 cursor-pointer focus:outline-none"
                  aria-expanded={isOpen}
                >
                  <span className="font-bold text-gray-900 text-base sm:text-lg flex items-center gap-3">
                    <span className="text-primary-600 font-semibold text-sm w-6">
                      {item.id}.
                    </span>
                    {item.question}
                  </span>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 transition-transform duration-200 ${
                    isOpen ? 'bg-primary-100 text-primary-700 rotate-180' : 'bg-gray-100 text-gray-500'
                  }`}>
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>
                {isOpen && (
                  <div className="px-6 pb-6 pt-1 pl-15 text-gray-600 text-sm sm:text-base leading-relaxed border-t border-gray-100">
                    {item.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Contact CTA Banner */}
        <div className="mt-14 p-8 rounded-3xl bg-cream-100 border border-gray-200 text-center space-y-4">
          <h3 className="text-xl font-bold text-gray-900">Still have questions?</h3>
          <p className="text-sm text-gray-600 max-w-md mx-auto">
            Can't find the answer you're looking for? Our support team is here to assist you.
          </p>
          <div className="flex flex-wrap justify-center gap-4 pt-2">
            <a 
              href="tel:8850347147"
              className="inline-flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white px-6 py-2.5 rounded-full font-semibold text-sm transition-colors shadow-sm"
            >
              <Phone className="w-4 h-4" />
              Call 8850347147
            </a>
            <Link 
              to="/#contact"
              className="inline-flex items-center gap-2 bg-white hover:bg-gray-50 text-gray-700 border border-gray-300 px-6 py-2.5 rounded-full font-semibold text-sm transition-colors"
            >
              <span>Contact Page</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default FAQPage;
